/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/downloads` | `/downloads`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-list` | `/my-list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/account/login`; params?: Router.UnknownInputParams; } | { pathname: `/legal`; params?: Router.UnknownInputParams; } | { pathname: `/m3u/categories`; params?: Router.UnknownInputParams; } | { pathname: `/m3u/source`; params?: Router.UnknownInputParams; } | { pathname: `/xtream/categories`; params?: Router.UnknownInputParams; } | { pathname: `/xtream/login`; params?: Router.UnknownInputParams; } | { pathname: `/m3u/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/player/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/series/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/xtream/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/downloads` | `/downloads`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-list` | `/my-list`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/account/login`; params?: Router.UnknownOutputParams; } | { pathname: `/legal`; params?: Router.UnknownOutputParams; } | { pathname: `/m3u/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/m3u/source`; params?: Router.UnknownOutputParams; } | { pathname: `/xtream/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/xtream/login`; params?: Router.UnknownOutputParams; } | { pathname: `/m3u/category/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/player/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/series/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/xtream/category/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/downloads${`?${string}` | `#${string}` | ''}` | `/downloads${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-list${`?${string}` | `#${string}` | ''}` | `/my-list${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/account/login${`?${string}` | `#${string}` | ''}` | `/legal${`?${string}` | `#${string}` | ''}` | `/m3u/categories${`?${string}` | `#${string}` | ''}` | `/m3u/source${`?${string}` | `#${string}` | ''}` | `/xtream/categories${`?${string}` | `#${string}` | ''}` | `/xtream/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/downloads` | `/downloads`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-list` | `/my-list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/account/login`; params?: Router.UnknownInputParams; } | { pathname: `/legal`; params?: Router.UnknownInputParams; } | { pathname: `/m3u/categories`; params?: Router.UnknownInputParams; } | { pathname: `/m3u/source`; params?: Router.UnknownInputParams; } | { pathname: `/xtream/categories`; params?: Router.UnknownInputParams; } | { pathname: `/xtream/login`; params?: Router.UnknownInputParams; } | `/m3u/category/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/player/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/series/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/xtream/category/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/m3u/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/player/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/series/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/xtream/category/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
